algoritmo "conversaodolar"
// Função :Converter a quantia em real para dolar.
// Autor : Rafaela Alves
// Data : 03/05/2022
// Seção de Declarações 
var
reais, dolar, conv: real

inicio
// Seção de Comandos
escreval("Informe o valor a converter:")
leia(reais)
escreval("Escreva o valor do dolar HOJE:")
leia(dolar)

//processamento

conv <- reais/dolar

//saída

escreval("O seu valor agora é: ",conv)
fimalgoritmo
