algoritmo "volei"
// Função :Você pode jogar volei?
// Autor :Rafaela Alves
// Data : 27/07/2022
// Seção de Declarações 
var

alt,idd: real

inicio

escreval("Informe sua idade")
leia(idd)
escreval("Informe sua altura")
leia(alt)

se (idd>=18) entao
 se (alt>=1.75) entao
   escreval("Pode participar,fique a vontade")
senao
   escreval("Sinto muito, hoje você só assiste")
fimse

fimalgoritmo
