Algoritmo "numeros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : cintia
// Descrição   : informar se o número mencionado é ímpar ou par
// Autor(a)    : Rafaela Alves
// Data atual  : 26/07/2022
Var
numero: inteiro

Inicio
escreval("Informe o número escolhido")
leia(numero)

se (numero mod 2=0)entao
    escreval("Esse número é PAR")
senao
     escreval("Esse número é ÍMPAR")
fimse

Fimalgoritmo