Algoritmo "AreaTriangulo"

// Descrição   : Calculo da area do triângulo
// Autor(a)    : Rafaela Alves
// Data atual  : 08/03/2022
Var
base, alt, area: real


Inicio
// Entrada

escreval("Informe a base do triângulo")
leia (base)
escreval ("Informe a altura do triângulo")
leia (alt)

// Processamento

area <- base*alt/2

// Saida

escreval ("A área do triângulo é: ", area)



Fimalgoritmo