Algoritmo "Media"
// Descrição   : média aritmética
// Autor(a)    : Rafaela Alves
// Data atual  : 08/03/2022
Var
n1, n2, n3, media: real


Inicio
// entrada

escreval ("Escreva o primeiro número.")
leia (n1)
escreval ("Escreva o segundo número.")
leia (n2)
escreval("Escreva o terceiro número.")
leia (n3)

// processamento

media <- (n1+n2+n3)/3

// saida

escreval ("Sua média aritmética é:", media)


Fimalgoritmo