Algoritmo "exe1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Contagem dos números
// Autor(a)    : Rafaela Alves
// Data atual  : 30/08/2022
Var
num1,num2,cont,acu: inteiro


Inicio
escreval("Informe o número para inicial:")
leia(num1)
escreval("Informe o número final para a contagem:")
leia(num2)

para cont de num1 ate num2 faca
    escreval("contando...")
    escreval(cont)
fimpara
Fimalgoritmo