Algoritmo "exe2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Monte a tabuada que deseja
// Autor(a)    : Rafaela Alves
// Data atual  : 31/08/2022
Var
num,res,cont: inteiro

Inicio
escreval("Informe o número que deseja ver a tabuada")
leia(num)



para cont de 1 ate 10 faca
 res <- num*cont
 escreval(num,"x",cont,"=",res)
fimpara

Fimalgoritmo